# Generated by Django 4.1.7 on 2023-02-22 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start1app', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='descc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='imgg',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='namee',
            new_name='name',
        ),
    ]
