# Generated by Django 4.1.7 on 2023-02-22 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start1app', '0003_rename_descc_team_desc_rename_imgg_team_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='desc',
            new_name='desc1',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='img',
            new_name='img1',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='name1',
        ),
    ]
